name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing ğŸ”§
        run: yarn
        
      - name: Lint ğŸ§
        run: yarn format
        
     - name: Testing server ğŸ§ª
       run: yarn test:server
       
     - name: Testing client ğŸ§ª
       run: cd client && yarn test
       
