name: CI

on: push



jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres
        env:  
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DATABASE: test

    steps:
      - uses: actions/checkout@v2

      - name: Installing ğŸ”§
        run: yarn
        
      - name: Lint ğŸ§
        run: yarn format
        
             
      - name: Testing client ğŸ§ª
        run: cd client && yarn test
        
      - name: Building server ğŸ—ï¸ 
        run: cd server && yarn build
      
      - name: Filling env
        run: cd server && touch .env
            && echo TEST_NAME="postgres" >> .env
            && echo TEST_PASSWORD="postgres" >> .env
            && echo TEST_DATABASE="test" >> .env
            && echo HOST="db" >> .env
            && echo JWT_SECRET="a secret" >> .env
            && cat .env
        
      - name: Testing client ğŸ§ª
        run: yarn test:server
  
       
