name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PORT: 5432

        ports:
          - 5432:5432

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Installing ğŸ”§
        run: |
          yarn install ----frozen-lockfile
          cd server
          yarn install ----frozen-lockfile
          cd ..
          cd client
          yarn install ----frozen-lockfile

      - name: Lint ğŸ§
        run: yarn format

      - name: Testing client ğŸ§ª
        run: cd client && yarn test

      - name: Building server ğŸ—ï¸
        run: cd server && yarn build

      - name: Filling env
        run: |
          cd server
          touch .env
          echo TEST_NAME="postgres" >> .env
          echo TEST_PASSWORD="postgres" >> .env
          echo TEST_DATABASE="test" >> .env
          echo HOST="localhost" >> .env
          echo JWT_SECRET="a secret" >> .env
          cat .env

      - name: Testing server ğŸ§ª
        run: yarn test:server
